Fix numpy version compatability error
This change fixes the following two errors:
======================================================================
ERROR: testTopTopics (gensim.test.test_ldamodel.TestLdaModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/nlp/gensim/gensim/test/test_ldamodel.py", line 218, in testTopTopics
    top_topics = self.model.top_topics(self.corpus)
  File "/home/ubuntu/nlp/gensim/gensim/models/ldamodel.py", line 874, in top_topics
    for l in top_words[:m_index - 1][0]:
TypeError: only integer scalar arrays can be converted to a scalar index

======================================================================
ERROR: testTopTopics (gensim.test.test_ldamodel.TestLdaMulticore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/nlp/gensim/gensim/test/test_ldamodel.py", line 218, in testTopTopics
    top_topics = self.model.top_topics(self.corpus)
  File "/home/ubuntu/nlp/gensim/gensim/models/ldamodel.py", line 874, in top_topics
    for l in top_words[:m_index - 1][0]:
"TypeError: only integer scalar arrays can be converted to a scalar index"